// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA71uC3YJDJPV38QJPpvhmCfBV_-q6qbX0',
    appId: '1:362156588672:web:6680d4572dab25ca75b065',
    messagingSenderId: '362156588672',
    projectId: 'flutter-firebase-auth-6457a',
    authDomain: 'flutter-firebase-auth-6457a.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-6457a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbH6knepRDh50XOAC2sOO_fQmyMKqvQHc',
    appId: '1:362156588672:android:5d7fc2eb9e31d2e175b065',
    messagingSenderId: '362156588672',
    projectId: 'flutter-firebase-auth-6457a',
    storageBucket: 'flutter-firebase-auth-6457a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuoiWm6aIBTf-Dn6BLTdAlbtB_QU9N_Hw',
    appId: '1:362156588672:ios:6da1473127a2a8b675b065',
    messagingSenderId: '362156588672',
    projectId: 'flutter-firebase-auth-6457a',
    storageBucket: 'flutter-firebase-auth-6457a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuoiWm6aIBTf-Dn6BLTdAlbtB_QU9N_Hw',
    appId: '1:362156588672:ios:6da1473127a2a8b675b065',
    messagingSenderId: '362156588672',
    projectId: 'flutter-firebase-auth-6457a',
    storageBucket: 'flutter-firebase-auth-6457a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA71uC3YJDJPV38QJPpvhmCfBV_-q6qbX0',
    appId: '1:362156588672:web:d52aeef0aa1c2a5875b065',
    messagingSenderId: '362156588672',
    projectId: 'flutter-firebase-auth-6457a',
    authDomain: 'flutter-firebase-auth-6457a.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-6457a.firebasestorage.app',
  );
}
